### ISSUE TITLE
No windows decorations are shown

### ISSUE THREAD

**Issue by CamilleScholtz** [vain/katriawm#3]
All build instructions and `*.h` I used can be found here: https://github.com/6c37/crux-ports-git/tree/3.2/katriawm

Like the title says, I start katriawm with xinit, spawn an URxvt window using an sxhkd shortcut, and it just spawns the window in the top left corner without any decorations. Is this the intended behavior, am I doing something wrong?

**Comment by vain** [comment]
That's not the intended behavior, I'm afraid. :) Your terminal should have decorations and you should be in tiling mode, i.e. the window should be maximized.

Can you provide the content of your xinitrc? Can you post the output of `xprop -root` during runtime (you should be able to type in your urxvt window, even though there's no WM)? Did you check `dmesg` to see if katriawm has crashed for some reason? Do you see a running `katriawm` process?

You can build with debugging enabled (`make DEBUG_CPPFLAGS=-DDEBUG DEBUG_CFLAGS=-g`) and then launch the WM using `katriawm >/tmp/katriawm.log 2>&1` in your xinitrc. Maybe this gives us a clue on what's going on.

Your build instructions look fine, however I'd expect to see something like the following, but I'm not familiar with Crux, so ...

``` diff
diff --git a/katriawm/Pkgfile b/katriawm/Pkgfile
index 9f02a10..5030495 100644
--- a/katriawm/Pkgfile
+++ b/katriawm/Pkgfile
@@ -28,7 +28,7 @@ build() {
        cp $SRC/barinfo_config.h barinfo/config.h
        cp $SRC/core_config.h core/config.h
        mkdir -p ../themes/theme
-       cp $SRC/{colorsfonts.h,decorations.ppm,layout.h,metadata} ../themes/theme
+       cp $SRC/theme/{colorsfonts.h,decorations.ppm,layout.h,metadata} ../themes/theme
        ../themes/make_theme_h.sh ../themes/theme > core/theme.h

        make
```

**Comment by CamilleScholtz** [comment]
.xinitrc

```
# Set wallpaper
wallshuf

# Load fonts
xset +fp /usr/share/fonts/X11/misc
xset +fp $HOME/.fonts
xset +fp $HOME/.fonts/Microsoft
xset fp rehash

# Load .Xresources
xrdb $HOME/.Xresources

# Start URxvt daemon
#urxvtd -q -o -f

# Add shadows
#compton -b --backend xrender --unredir-if-possible -cC -l -18 -t -18 -o 0.07

# Start lemonbars
#fish $HOME/.lemonbar/launcher &

# Start hotkey daemon
sxhkd -c $HOME/.sxhkdrc

# Start wm
exec katriawm
```

xprop -root

```
RESOURCE_MANAGER(STRING) = "*perl-ext-common:\tdefault,matcher\n*url-launcher:\tseamonkey\n*matcher.button:\t1\n*scrollBar:\tfalse\n*internalBorder:\t23\n*geometry:\t75x14\n*font:\t-windows-dina-medium-r-normal--13-80-96-96-c-70-microsoft-cp1252,-FreeType-JackeyFont-Medium-R-Normal--12-90-100-100-P-21-ISO10646-1\n*boldFont:\t\n*italicFont:\t\n*boldItalicFont:\t\n*lineSpace:\t8\n*cursorUnderline:\ttrue\n*foreground:\t#E8DFD6\n*background:\t#212F31\n*cursorColor:\t#F3D5C9\n*highlightColor:\t#2A4141\n*highlightTextColor:\t#F2F1B9\n*color0:\t#2A4141\n*color8:\t#435858\n*color1:\t#F99595\n*color9:\t#F3D5C9\n*color2:\t#7CBF9E\n*color10:\t#A2D9B1\n*color3:\t#E5C078\n*color11:\t#F9D48C\n*color4:\t#7BBAC7\n*color12:\t#DFF0EB\n*color5:\t#FF5879\n*color13:\t#FF99A1\n*color6:\t#62BDB3\n*color14:\t#9ED9D8\n*color7:\t#F2F1B9\n*color15:\t#F6F6C9\n"
_SETROOTPMAP_ID(PIXMAP): pixmap id # 0x400001
_XROOTPMAP_ID(PIXMAP): pixmap id # 0x400001
_XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""
XFree86_has_VT(INTEGER) = 1
XFree86_VT(INTEGER) = 7
```

I should also note katriawm prints `Could not find window with _NET_WM_WINDOW_TYPE set. Defaulting to root window.` on startup.

About the diff, CRUX copies all the files listen source= to the work directory, so thta line is actually correct :).

EDIT: So I just made some progress, `pgrep katriawm` returns nothing, running `katriawm` manually in the term actually starts katriawm, with decorations and all.

**Comment by vain** [comment]
The `Could not find window with _NET_WM_WINDOW_TYPE set. Defaulting to root window.` line sounds like it's coming from https://github.com/ttzhou/setroot.

I think the problem with your setup is that `sxhkd` does not fork. It blocks. Hence, your xinitrc does not reach the point where it would run `exec katriawm`. :) The fact that there is no `_KATRIA_STATE` property on the root window supports the theory that there's no WM running. 

Have you tried `sxhkd -c ... &`?

Also note that I'm not very happy with "the sxhkd situation", as mentioned in #2. You should probably stick with version 0.5.5 of sxhkd if you plan on configuring mouse support.

**Comment by CamilleScholtz** [comment]
Ah you are completely right, I haven't used sxhkd in a long time so I forgot about it. Sorry!

About mouse movement, check out: https://github.com/wmutils/opt/blob/master/xmmv.c
