### ISSUE TITLE
Feature request: make it possible to set the initial layout style.

### ISSUE THREAD

**Issue by CamilleScholtz** [vain/katriawm#5]
I noticed that I can change it in `include/ipc.h`, however something like

```
enum LayoutAlgorithm
{
    LAFloat = 0,
    LATile,
    LAMonocle,

    LALast,
};
```

seems to break all layouts besides floating..

**Comment by vain** [comment]
I agree, it'd be better if a user could set this in his `config.h`. `ipc.h` is an arcane location for a user setting. I'll push a commit soon.

Nevertheless, your change actually works for me. You sure you rebuilt and restarted everything, including the client? If something does indeed break when re-ordering those constants, then there's a bug somewhere which should be fixed.
